#!/bin/bash
cd ${0%/*} || exit 1    # run from this directory



# Check if OpenFOAM/FOAM has been sourced
if [[ -z "${WM_PROJECT}" ]]
then
    echo "Please source the OpenFOAM/FOAM bashrc first!"
    exit 1 
fi

# Compile solvers
cd src/solvers/biotQSFoam  && wmake
cd ~/Projects/NuLIMAS_GIT
cd src/solvers/residualLiquefactionQSFoam  && wmake
cd ~/Projects/NuLIMAS_GIT
cd src/solvers/pressureBuildupFoam  && wmake
cd ~/Projects/NuLIMAS_GIT
cd src/solvers/residualLiquefactionFDDyMFoam && wmake
cd ~/Projects/NuLIMAS_GIT
cd src/solvers/rockerFoam && wmake
cd ~/Projects/NuLIMAS_GIT

# Compile boundaries
cd src/boundaries && wmake libso
cd ~/Projects/NuLIMAS_GIT

# Compile mesh files
cd src/mesh && wmake libso
