#!/bin/bash
cd ${0%/*} || exit 1    # run from this directory



# Check if OpenFOAM/FOAM has been sourced
if [[ -z "${WM_PROJECT}" ]]
then
    echo "Please source the OpenFOAM/FOAM bashrc first!"
    exit 1 
fi

# Compile solvers
cd src/solvers/biotQSFoam  && wmake
cd ..
cd residualLiquefactionQSFoam  && wmake
cd ..
cd pressureBuildupFoam  && wmake
cd ..
cd residualLiquefactionFDDyMFoam && wmake
cd ..
cd liquefactionQSFoam && wmake
cd ..
cd rockerFoam && wmake
cd ../../

# Compile boundaries
cd boundaries && wmake libso
cd ../

# Compile mesh files
cd mesh && wmake libso
