#!/bin/bash
cd ${0%/*} || exit 1    # run from this directory



# Check if OpenFOAM/FOAM has been sourced
if [[ -z "${WM_PROJECT}" ]]
then
    echo "Please source the OpenFOAM/FOAM bashrc first!"
    exit 1 
fi

# Compile solvers
cd src/solvers/biotQSFoam  && wclean
cd ..
cd residualLiquefactionQSFoam  && wclean
cd ..
cd pressureBuildupFoam  && wclean
cd ..
cd liquefactionQSFoam && wclean
cd ..
cd liqueCompactionDyMFoam && wclean
cd ../../

# Compile boundaries
cd boundaries && wclean
cd ../

# Compile mesh files
cd mesh && wclean 
