#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

#application="biotFoam"

#cp -r 0.org 0
runApplication blockMesh
runApplication setSet < batch.setSet
runApplication setsToZones -noFlipMap
runApplication residualLiquefactionFDDyMFoam &


#runApplication decomposePar
#runApplication mpirun -np 8 $application -parallel > log &




