#!/bin/bash
cd ${0%/*} || exit 1    # run from this directory



# Check if OpenFOAM/FOAM has been sourced
if [[ -z "${WM_PROJECT}" ]]
then
    echo "Please source the OpenFOAM/FOAM bashrc first!"
    exit 1 
fi

# Compile solvers
wclean  solvers/biotQSFoam  
wclean  solvers/residualLiquefactionFoam
wclean  solvers/initialConsolidationFoam
wclean  solvers/structFoam 

# Compile boundaries
cd boundaries && wclean
cd ../

# Compile mesh files
cd mesh && wclean 
