#!/bin/bash
cd ${0%/*} || exit 1    # run from this directory



# Check if OpenFOAM/FOAM has been sourced
if [[ -z "${WM_PROJECT}" ]]
then
    echo "Please source the OpenFOAM/FOAM bashrc first!"
    exit 1 
fi

# Compile solvers
wmake  solvers/biotQSFoam  
wmake  solvers/residualLiquefactionFoam
wmake  solvers/initialConsolidationFoam
wmake  solvers/structFoam 
wmake  solvers/structDyMFoam 
wmake  solvers/liqueCompactionDyMFoam 


# Compile boundaries
cd boundaries && wmake libso
cd ../

# Compile mesh files
cd mesh && wmake libso
