#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm alpha.txt
rm liquefactionDepth.txt

runApplication blockMesh
runApplication setSet < batch.setSet
runApplication setsToZones -noFlipMap
runApplication liqueCompactionDyMFoam &


#runApplication decomposePar
#runApplication mpirun -np 8 $application -parallel > log &




